// src/components/dashboard/SideBar.vue
<script lang="ts" setup>
import { RouterLink, useRouter } from "vue-router";

const router = useRouter();
const props = defineProps<{
  linear?: boolean;
  setLinear?: (val: boolean) => void;
  active: string;
}>();

const navigate = (path: string) => {
  props.setLinear && props.setLinear(true);
  router.push(path);
};

const goHome = () => router.push("/dashboard");
</script>

<template>
  <div
    class="flex flex-col py-3 justify-between border-r-2 border-[#d6d3da] px-1"
  >
    <div class="flex flex-col">
      <!-- Logo Section -->
      <RouterLink
        to="/"
        class="flex items-center gap-2 cursor-pointer mt-4 px-3"
      >
        <img class="w-6 h-6" src="../../assets/logo.png" alt="Travella logo" />
        <h2
          class="font-bold text-lg md:text-2xl text-gray-800 xtab:flex hidden"
        >
          Travella
        </h2>
      </RouterLink>

      <!-- Navigation Buttons -->
      <div class="mt-11 flex flex-col">
        <button
          @click="() => navigate('/dashboard')"
          :class="`flex rounded-lg w-fit xtab:w-[unset] hover:bg-active hover:text-white duration-300 mt-1 items-center px-3 py-2 ${
            active === 'home' && 'bg-active text-white'
          }`"
        >
          <v-icon
            size="14"
            :class="active === 'home' ? 'text-white' : `text`"
            icon="fas fa-home"
          />
          <p class="ml-4 truncate text-sm xtab:flex hidden items-end">Home</p>
        </button>
        <button
          @click="() => navigate('/search')"
          :class="`flex rounded-lg w-fit xtab:w-[unset] hover:bg-active hover:text-white duration-300 mt-1 items-center px-3 py-2 ${
            active === 'search' && 'bg-active text-white'
          }`"
        >
          <v-icon
            size="14"
            :class="active === 'search' ? 'text-white' : `text`"
            icon="fas fa-search"
          />
          <p class="ml-4 truncate text-sm xtab:flex hidden items-end">
            Find Places
          </p>
        </button>
        <button
          @click="() => navigate('/notifications')"
          :class="`flex rounded-lg w-fit xtab:w-[unset] hover:bg-active hover:text-white duration-300 mt-1 items-center px-3 py-2 ${
            active === 'notifications' && 'bg-active text-white'
          }`"
        >
          <v-icon
            size="14"
            :class="active === 'notification' ? 'text-white' : `text`"
            icon="fas fa-bell"
          />
          <p class="ml-4 truncate text-sm xtab:flex hidden items-end">
            Notification
          </p>
        </button>
        <button
          @click="() => navigate('/saved')"
          :class="`flex rounded-lg w-fit xtab:w-[unset] hover:bg-active hover:text-white duration-300 mt-1 items-center px-3 py-2 ${
            active === 'saved' && 'bg-active text-white'
          }`"
        >
          <v-icon
            size="14"
            :class="active === 'saved' ? 'text-white' : `text`"
            icon="fas fa-heart"
          />
          <p class="ml-4 truncate text-sm xtab:flex hidden items-end">
            Saved Places
          </p>
        </button>
        <button
          @click="() => navigate('/account')"
          :class="`flex rounded-lg w-fit xtab:w-[unset] hover:bg-active hover:text-white duration-300 mt-1 items-center px-3 py-2 ${
            active === 'account' && 'bg-active text-white'
          }`"
        >
          <v-icon
            size="14"
            :class="active === 'account' ? 'text-white' : `text`"
            icon="fas fa-user"
          />
          <p class="ml-4 truncate text-sm xtab:flex hidden items-end">
            Account
          </p>
        </button>
      </div>
    </div>

    <!-- Upgrade to Pro Button -->
    <div class="flex flex-col">
      <button
        class="flex w-fit xtab:w-[unset] justify-center rounded-lg items-center px-3 py-2 bg-active text-white text-sm"
      >
        <span class="xtab:flex hidden">Upgrade to Pro</span>
        <v-icon
          size="14"
          class="text-white xtab:hidden"
          icon="fas fa-paper-plane"
        />
      </button>
    </div>
  </div>
</template>

// travelFronted/src/User/Sidebar.tsx
import { useState } from "react";
import { Link } from "react-router-dom";

import logo from "../assets/logo.png";
import { useAuth } from "../Auth/AuthContext";

import { IoClose, IoMenu } from "react-icons/io5";
import { IoMdHome } from "react-icons/io";
import { FaSearch } from "react-icons/fa";
import { FaHeart } from "react-icons/fa6";
import { MdAccountBox } from "react-icons/md";
import { FiLogOut } from "react-icons/fi";

export const Navbar = () => {
  const [isOpen, setIsOpen] = useState<boolean>(false);

  const { logout } = useAuth();

  const sideLinks = [
    { name: "Home", link: "/user", icon: <IoMdHome /> },
    { name: "Find Places", link: "#", icon: <FaSearch /> },
    { name: "Saved Places", link: "/saved", icon: <FaHeart /> },
    { name: "Account", link: "/user/profile", icon: <MdAccountBox /> },
  ];

  return (
    <div className="">
      <div className="">
        <div className="px-3 flex items-center gap-[200px] md:gap-0 mb-4">
          <div
            onClick={() => setIsOpen(!isOpen)}
            className="text-2xl text-gray-900 md:hidden cursor-pointer"
          >
            {isOpen ? <IoClose /> : <IoMenu />}
          </div>

          <Link to={"/user"} className="flex items-center gap-2">
            <img className="w-8 h-8" src={logo} alt="Travella logo" />
            <h2 className="font-bold text-xl md:text-2xl text-gray-800">
              Travella
            </h2>
          </Link>
        </div>

        <hr className="text-gray-600" />
      </div>

      {/* the links */}
      <div
        className={`border-r border-gray-400 left-[-100%] md:left-[0] w-[200px] h-[550px] px-3 pt-5 transition-all duration-500 fixed ${
          isOpen ? "left-[0]" : ""
        }`}
      >
        <div className="flex flex-col gap-4">
          {sideLinks.map((li, i) => (
            <Link
              to={li.link}
              key={i}
              className="flex items-center gap-2 text-gray-800 hover:text-sky-500 duration-500"
            >
              <span className="text-xl ">{li.icon}</span>
              <span className="font-semibold text-[17px]">{li.name} </span>
            </Link>
          ))}
        </div>

        <div
          className="my-5 text-white px-3 py-2 rounded-md mx-5 flex gap-2 items-center font-semibold bg-sky-600 hover:bg-sky-900 duration-500 cursor-pointer"
          onClick={logout}
        >
          <FiLogOut />
          <span>Logout</span>
        </div>
      </div>
    </div>
  );
};
